create table products (
    id bigint generated by default as identity,
    name varchar(100) not null,
    price numeric(19, 2) not null,
    status varchar(20) not null,
    content_title varchar(100) not null,
    content_type varchar(30) not null,
    category varchar(50) not null,
    description varchar(1000),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_products primary key (id),
    constraint chk_products_price_positive check (price > 0),
    constraint chk_products_status check (status in ('ON_SALE', 'STOPPED')),
    constraint chk_products_content_type check (content_type in ('WEBTOON', 'WEB_NOVEL', 'MOVIE', 'DRAMA', 'MUSIC', 'ETC'))
);

create table stocks (
    id bigint generated by default as identity,
    product_id bigint not null,
    quantity bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_stocks primary key (id),
    constraint fk_stocks_product foreign key (product_id) references products (id),
    constraint uk_stocks_product_id unique (product_id),
    constraint chk_stocks_quantity_non_negative check (quantity >= 0)
);

create index idx_products_status on products (status);
create index idx_products_content_type on products (content_type);
