create table carts (
    id bigint generated by default as identity,
    customer_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_carts primary key (id),
    constraint uk_carts_customer_id unique (customer_id),
    constraint chk_carts_customer_id_positive check (customer_id > 0)
);

create table cart_items (
    id bigint generated by default as identity,
    cart_id bigint not null,
    product_id bigint not null,
    quantity bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_cart_items primary key (id),
    constraint fk_cart_items_cart foreign key (cart_id) references carts (id) on delete cascade,
    constraint fk_cart_items_product foreign key (product_id) references products (id),
    constraint uk_cart_items_cart_product unique (cart_id, product_id),
    constraint chk_cart_items_quantity_positive check (quantity > 0)
);

create index idx_cart_items_product_id on cart_items (product_id);
