create table orders (
    id bigint generated by default as identity,
    customer_id bigint not null,
    status varchar(30) not null,
    expires_at timestamp not null,
    cancel_reason varchar(30),
    total_product_amount numeric(19, 2) not null,
    total_instant_discount_amount numeric(19, 2) not null,
    total_coupon_discount_amount numeric(19, 2) not null,
    final_payment_amount numeric(19, 2) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_orders primary key (id),
    constraint chk_orders_customer_id_positive check (customer_id > 0),
    constraint chk_orders_status check (status in ('PAYMENT_PENDING', 'COMPLETED', 'CANCELED')),
    constraint chk_orders_cancel_reason check (cancel_reason is null or cancel_reason in ('PAYMENT_CANCELED', 'PAYMENT_EXPIRED')),
    constraint chk_orders_total_product_amount_non_negative check (total_product_amount >= 0),
    constraint chk_orders_total_instant_discount_amount_non_negative check (total_instant_discount_amount >= 0),
    constraint chk_orders_total_coupon_discount_amount_non_negative check (total_coupon_discount_amount >= 0),
    constraint chk_orders_final_payment_amount_non_negative check (final_payment_amount >= 0)
);

create table order_items (
    id bigint generated by default as identity,
    order_id bigint not null,
    product_id bigint not null,
    product_name varchar(100) not null,
    product_price numeric(19, 2) not null,
    quantity bigint not null,
    original_amount numeric(19, 2) not null,
    instant_discount_amount numeric(19, 2) not null,
    product_coupon_discount_amount numeric(19, 2) not null,
    final_amount numeric(19, 2) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_order_items primary key (id),
    constraint fk_order_items_order foreign key (order_id) references orders (id) on delete cascade,
    constraint fk_order_items_product foreign key (product_id) references products (id),
    constraint chk_order_items_quantity_positive check (quantity > 0),
    constraint chk_order_items_product_price_positive check (product_price > 0),
    constraint chk_order_items_original_amount_non_negative check (original_amount >= 0),
    constraint chk_order_items_instant_discount_amount_non_negative check (instant_discount_amount >= 0),
    constraint chk_order_items_product_coupon_discount_amount_non_negative check (product_coupon_discount_amount >= 0),
    constraint chk_order_items_final_amount_non_negative check (final_amount >= 0)
);

create index idx_orders_customer_id on orders (customer_id);
create index idx_orders_status_expires_at on orders (status, expires_at);
create index idx_order_items_product_id on order_items (product_id);
