create table coupons (
    id bigint generated by default as identity,
    name varchar(100) not null,
    type varchar(20) not null,
    discount_amount numeric(19, 2) not null,
    target_product_id bigint,
    expires_at timestamp not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_coupons primary key (id),
    constraint fk_coupons_target_product foreign key (target_product_id) references products (id),
    constraint chk_coupons_type check (type in ('ORDER', 'PRODUCT')),
    constraint chk_coupons_discount_amount_positive check (discount_amount > 0),
    constraint chk_coupons_target_product_by_type check (
        (type = 'ORDER' and target_product_id is null)
        or (type = 'PRODUCT' and target_product_id is not null)
    )
);

create table issued_coupons (
    id bigint generated by default as identity,
    coupon_id bigint not null,
    customer_id bigint not null,
    order_id bigint,
    status varchar(20) not null,
    issued_at timestamp not null,
    reserved_at timestamp,
    used_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_issued_coupons primary key (id),
    constraint fk_issued_coupons_coupon foreign key (coupon_id) references coupons (id),
    constraint fk_issued_coupons_order foreign key (order_id) references orders (id),
    constraint chk_issued_coupons_customer_id_positive check (customer_id > 0),
    constraint chk_issued_coupons_status check (status in ('AVAILABLE', 'RESERVED', 'USED', 'EXPIRED')),
    constraint chk_issued_coupons_reserved_order check (
        (status = 'RESERVED' and order_id is not null and reserved_at is not null)
        or status <> 'RESERVED'
    ),
    constraint chk_issued_coupons_used_at check (
        (status = 'USED' and order_id is not null and reserved_at is not null and used_at is not null)
        or status <> 'USED'
    )
);

create index idx_coupons_target_product_id on coupons (target_product_id);
create index idx_issued_coupons_customer_status on issued_coupons (customer_id, status);
create index idx_issued_coupons_order_id on issued_coupons (order_id);
