create table product_discounts (
    id bigint generated by default as identity,
    product_id bigint not null,
    name varchar(100) not null,
    discount_amount numeric(19, 2) not null,
    starts_at timestamp not null,
    ends_at timestamp not null,
    active boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint pk_product_discounts primary key (id),
    constraint fk_product_discounts_product foreign key (product_id) references products (id),
    constraint uk_product_discounts_product_id unique (product_id),
    constraint chk_product_discounts_discount_amount_positive check (discount_amount > 0),
    constraint chk_product_discounts_period check (ends_at > starts_at)
);

create index idx_product_discounts_active_period on product_discounts (active, starts_at, ends_at);
